// <copyright file="Leaderboards.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_hightestLevels = new UnifiedLeaderboard("hightestLevels",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI54LlrKETEAIQAA"
#else
            "hightestLevels"
#endif
            );

        public static UnifiedLeaderboard hightestLevels
        {
            get { return s_hightestLevels; }
        }

        private static readonly UnifiedLeaderboard s_coinsLeaderboard = new UnifiedLeaderboard("coinsLeaderboard",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI54LlrKETEAIQAw"
#else
            "coinsLeaderboard"
#endif
            );

        public static UnifiedLeaderboard coinsLeaderboard
        {
            get { return s_coinsLeaderboard; }
        }

        public static string GetPlatformID(string internalId)
        {
            return s_leaderboardDictionary.ContainsKey(internalId)
                ? s_leaderboardDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedLeaderboard> s_leaderboardDictionary = new Dictionary<string, UnifiedLeaderboard>
        {
            { "hightestLevels", s_hightestLevels },
            { "coinsLeaderboard", s_coinsLeaderboard },
        };
    }
}
